# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dgp/proto/metadata.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='dgp/proto/metadata.proto',
  package='pd.totoro',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x18\x64gp/proto/metadata.proto\x12\tpd.totoro\"m\n\rSceneMetadata\x12\x0f\n\x07\x63ountry\x18\x01 \x01(\t\x12\x11\n\tsensor_id\x18\x02 \x01(\t\x12\x13\n\x0btime_of_day\x18\x03 \x01(\t\x12#\n\x07weather\x18\x04 \x01(\x0b\x32\x12.pd.totoro.Weather\"B\n\x07Weather\x12\x0e\n\x06\x63louds\x18\x01 \x01(\x01\x12\x0c\n\x04rain\x18\x02 \x01(\x01\x12\x0c\n\x04snow\x18\x03 \x01(\x01\x12\x0b\n\x03\x66og\x18\x04 \x01(\x01\"\xdf\x01\n\x13\x43\x61meraFrameMetadata\x12\x0c\n\x04road\x18\x01 \x01(\t\x12\x13\n\x0bpartition_0\x18\x02 \x01(\t\x12\x13\n\x0blane_change\x18\x03 \x01(\x08\x12\x19\n\x11\x62ranching_in_view\x18\x04 \x01(\x08\x12\x13\n\x0b\x65go_merging\x18\x05 \x01(\x08\x12\x17\n\x0fmerging_in_view\x18\x06 \x01(\x08\x12\x1b\n\x13\x65levation_variation\x18\x07 \x01(\x08\x12\x15\n\rtype_of_scene\x18\x08 \x01(\t\x12\x13\n\x0broad_radius\x18\t \x01(\x01\x62\x06proto3'
)




_SCENEMETADATA = _descriptor.Descriptor(
  name='SceneMetadata',
  full_name='pd.totoro.SceneMetadata',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='country', full_name='pd.totoro.SceneMetadata.country', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sensor_id', full_name='pd.totoro.SceneMetadata.sensor_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='time_of_day', full_name='pd.totoro.SceneMetadata.time_of_day', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='weather', full_name='pd.totoro.SceneMetadata.weather', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=148,
)


_WEATHER = _descriptor.Descriptor(
  name='Weather',
  full_name='pd.totoro.Weather',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='clouds', full_name='pd.totoro.Weather.clouds', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='rain', full_name='pd.totoro.Weather.rain', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='snow', full_name='pd.totoro.Weather.snow', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='fog', full_name='pd.totoro.Weather.fog', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=150,
  serialized_end=216,
)


_CAMERAFRAMEMETADATA = _descriptor.Descriptor(
  name='CameraFrameMetadata',
  full_name='pd.totoro.CameraFrameMetadata',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='road', full_name='pd.totoro.CameraFrameMetadata.road', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='partition_0', full_name='pd.totoro.CameraFrameMetadata.partition_0', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='lane_change', full_name='pd.totoro.CameraFrameMetadata.lane_change', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='branching_in_view', full_name='pd.totoro.CameraFrameMetadata.branching_in_view', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ego_merging', full_name='pd.totoro.CameraFrameMetadata.ego_merging', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='merging_in_view', full_name='pd.totoro.CameraFrameMetadata.merging_in_view', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='elevation_variation', full_name='pd.totoro.CameraFrameMetadata.elevation_variation', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='type_of_scene', full_name='pd.totoro.CameraFrameMetadata.type_of_scene', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='road_radius', full_name='pd.totoro.CameraFrameMetadata.road_radius', index=8,
      number=9, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=219,
  serialized_end=442,
)

_SCENEMETADATA.fields_by_name['weather'].message_type = _WEATHER
DESCRIPTOR.message_types_by_name['SceneMetadata'] = _SCENEMETADATA
DESCRIPTOR.message_types_by_name['Weather'] = _WEATHER
DESCRIPTOR.message_types_by_name['CameraFrameMetadata'] = _CAMERAFRAMEMETADATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SceneMetadata = _reflection.GeneratedProtocolMessageType('SceneMetadata', (_message.Message,), {
  'DESCRIPTOR' : _SCENEMETADATA,
  '__module__' : 'dgp.proto.metadata_pb2'
  # @@protoc_insertion_point(class_scope:pd.totoro.SceneMetadata)
  })
_sym_db.RegisterMessage(SceneMetadata)

Weather = _reflection.GeneratedProtocolMessageType('Weather', (_message.Message,), {
  'DESCRIPTOR' : _WEATHER,
  '__module__' : 'dgp.proto.metadata_pb2'
  # @@protoc_insertion_point(class_scope:pd.totoro.Weather)
  })
_sym_db.RegisterMessage(Weather)

CameraFrameMetadata = _reflection.GeneratedProtocolMessageType('CameraFrameMetadata', (_message.Message,), {
  'DESCRIPTOR' : _CAMERAFRAMEMETADATA,
  '__module__' : 'dgp.proto.metadata_pb2'
  # @@protoc_insertion_point(class_scope:pd.totoro.CameraFrameMetadata)
  })
_sym_db.RegisterMessage(CameraFrameMetadata)


# @@protoc_insertion_point(module_scope)
